export const SESSION = {
  PROJECT_NAME_TOKEN: "PROJECT_NAME__TOKEN",
  PROJECT_NAME_ROLE: "PROJECT_NAME__ROLE",
  PROJECT_NAME_LABEL: "PROJECT_NAME",
  PROJECT_NAME_EMPLOYEEID: "PROJECT_NAME__EMPLOYEEID",
  PROJECT_NAME_REFRESH_TOKEN: "PROJECT_NAME__REFRESH_TOKEN",
};
